"""
=============================================================
TTC Transit Delay Analytics Pipeline
Phase 4: Interactive Dash Dashboard
=============================================================
Author : Setu Patel
Requires: ttc_delays.db (generated by phase1_ingest.py)
Run    : python phase4_dashboard.py
Visit  : http://127.0.0.1:8050
=============================================================
"""

import sqlite3
import pandas as pd
import dash
from dash import dcc, html, Input, Output, dash_table
import plotly.graph_objects as go
import plotly.express as px

DB_PATH = "ttc_delays.db"

# ── Palette ────────────────────────────────────────────────
BUS_COL  = "#E8512A"
SUB_COL  = "#1B6CA8"
ACCENT   = "#F5C400"
BG       = "#0F0F0F"
CARD_BG  = "#1A1A1A"
TEXT     = "#F0F0F0"
GRID     = "#2A2A2A"

PLOTLY_THEME = dict(
    paper_bgcolor=BG,
    plot_bgcolor=CARD_BG,
    font=dict(color=TEXT, family="Arial"),
    xaxis=dict(gridcolor=GRID, zerolinecolor=GRID),
    yaxis=dict(gridcolor=GRID, zerolinecolor=GRID),
    margin=dict(l=40, r=20, t=40, b=40),
)


# ── Data loading helpers ───────────────────────────────────
def query(sql):
    conn = sqlite3.connect(DB_PATH)
    df = pd.read_sql(sql, conn)
    conn.close()
    return df


def get_months():
    df = query("""
        SELECT DISTINCT year, month,
               year || '-' || printf('%02d', month) AS ym
        FROM bus_delays
        UNION
        SELECT DISTINCT year, month,
               year || '-' || printf('%02d', month)
        FROM subway_delays
        ORDER BY year, month
    """)
    return sorted(df["ym"].tolist())

MONTHS = get_months()
DOW_ORDER = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]


# ── App layout ─────────────────────────────────────────────
app = dash.Dash(__name__, title="TTC Delay Analytics")
app.layout = html.Div(style={"backgroundColor": BG, "minHeight": "100vh",
                              "fontFamily": "Arial, sans-serif", "color": TEXT}, children=[

    # ── Header ──
    html.Div(style={"backgroundColor": CARD_BG, "padding": "20px 40px",
                    "borderBottom": f"3px solid {ACCENT}",
                    "display": "flex", "alignItems": "center", "gap": "16px"}, children=[
        html.Div("🚌", style={"fontSize": "32px"}),
        html.Div([
            html.H1("TTC Delay Analytics", style={"margin": 0, "color": ACCENT,
                                                   "fontSize": "24px", "fontWeight": "bold"}),
            html.P("Toronto Transit Commission · 2025–2026",
                   style={"margin": 0, "color": TEXT, "opacity": "0.6", "fontSize": "13px"}),
        ]),
        html.Div(style={"marginLeft": "auto", "display": "flex", "gap": "12px",
                        "alignItems": "center"}, children=[
            html.Label("Transit Mode:", style={"fontSize": "13px", "opacity": "0.7"}),
            dcc.Dropdown(
                id="mode-filter",
                options=[
                    {"label": "🚌  Bus",    "value": "bus"},
                    {"label": "🚇  Subway", "value": "subway"},
                ],
                value="bus",
                clearable=False,
                style={"width": "160px", "backgroundColor": CARD_BG,
                       "color": "#000", "border": f"1px solid {GRID}"},
            ),
            html.Label("Date Range:", style={"fontSize": "13px", "opacity": "0.7"}),
            dcc.RangeSlider(
                id="month-slider",
                min=0, max=len(MONTHS)-1,
                value=[0, len(MONTHS)-1],
                marks={i: {"label": m if i % 3 == 0 else "",
                           "style": {"color": TEXT, "fontSize": "10px"}}
                       for i, m in enumerate(MONTHS)},
                tooltip={"placement": "bottom", "always_visible": False},
            ),
        ]),
    ]),

    # ── KPI Cards ──
    html.Div(id="kpi-cards", style={"display": "flex", "gap": "16px",
                                     "padding": "24px 40px 8px"}),

    # ── Row 1: Hourly + DOW ──
    html.Div(style={"display": "flex", "gap": "16px", "padding": "8px 40px"}, children=[
        html.Div(dcc.Graph(id="hourly-chart", config={"displayModeBar": False}),
                 style={"flex": "1", "backgroundColor": CARD_BG,
                        "borderRadius": "8px", "padding": "8px"}),
        html.Div(dcc.Graph(id="dow-chart", config={"displayModeBar": False}),
                 style={"flex": "1", "backgroundColor": CARD_BG,
                        "borderRadius": "8px", "padding": "8px"}),
    ]),

    # ── Row 2: Monthly trend ──
    html.Div(style={"padding": "8px 40px"}, children=[
        html.Div(dcc.Graph(id="monthly-chart", config={"displayModeBar": False}),
                 style={"backgroundColor": CARD_BG, "borderRadius": "8px", "padding": "8px"}),
    ]),

    # ── Row 3: Top routes/stations + worst delays table ──
    html.Div(style={"display": "flex", "gap": "16px", "padding": "8px 40px 32px"}, children=[
        html.Div(dcc.Graph(id="top-chart", config={"displayModeBar": False}),
                 style={"flex": "1", "backgroundColor": CARD_BG,
                        "borderRadius": "8px", "padding": "8px"}),
        html.Div([
            html.H4("⚠️ Worst Delays", style={"color": ACCENT, "margin": "8px 0 12px",
                                               "fontSize": "14px"}),
            dash_table.DataTable(
                id="worst-table",
                style_table={"overflowX": "auto"},
                style_cell={"backgroundColor": CARD_BG, "color": TEXT,
                            "border": f"1px solid {GRID}", "fontSize": "12px",
                            "padding": "6px 10px", "textAlign": "left"},
                style_header={"backgroundColor": BG, "color": ACCENT,
                              "fontWeight": "bold", "border": f"1px solid {GRID}"},
                style_data_conditional=[{
                    "if": {"row_index": 0},
                    "backgroundColor": "#2a1800", "color": ACCENT,
                }],
                page_size=8,
            ),
        ], style={"flex": "1", "backgroundColor": CARD_BG,
                  "borderRadius": "8px", "padding": "16px"}),
    ]),
])


# ── Callbacks ──────────────────────────────────────────────
def month_where(start_ym, end_ym, table):
    sy, sm = start_ym.split("-")
    ey, em = end_ym.split("-")
    return f"""
        (year > {sy} OR (year = {sy} AND month >= {sm}))
        AND (year < {ey} OR (year = {ey} AND month <= {em}))
    """


@app.callback(
    Output("kpi-cards", "children"),
    Output("hourly-chart", "figure"),
    Output("dow-chart", "figure"),
    Output("monthly-chart", "figure"),
    Output("top-chart", "figure"),
    Output("worst-table", "data"),
    Output("worst-table", "columns"),
    Input("mode-filter", "value"),
    Input("month-slider", "value"),
)
def update_all(mode, month_range):
    table  = "bus_delays" if mode == "bus" else "subway_delays"
    color  = BUS_COL if mode == "bus" else SUB_COL
    start  = MONTHS[month_range[0]]
    end    = MONTHS[month_range[1]]
    where  = month_where(start, end, table)

    # ── KPIs ──
    kpi = query(f"""
        SELECT COUNT(*) AS incidents,
               ROUND(AVG(delay_minutes),1) AS avg_delay,
               MAX(delay_minutes) AS max_delay,
               ROUND(SUM(delay_minutes)/60.0,0) AS total_hours
        FROM {table} WHERE delay_minutes > 0 AND {where}
    """).iloc[0]

    def kpi_card(label, value, unit=""):
        return html.Div(style={
            "backgroundColor": CARD_BG, "borderRadius": "8px",
            "padding": "16px 24px", "flex": "1",
            "borderTop": f"3px solid {color}",
        }, children=[
            html.P(label, style={"margin": "0 0 4px", "opacity": "0.6", "fontSize": "12px"}),
            html.H3(f"{value}{unit}", style={"margin": 0, "color": color,
                                              "fontSize": "28px", "fontWeight": "bold"}),
        ])

    cards = [
        kpi_card("Total Incidents",    f"{int(kpi.incidents):,}"),
        kpi_card("Avg Delay",          kpi.avg_delay, " min"),
        kpi_card("Worst Single Delay", int(kpi.max_delay), " min"),
        kpi_card("Total Delay",        f"{int(kpi.total_hours):,}", " hrs"),
    ]

    # ── Hourly ──
    hourly = query(f"""
        SELECT hour, COUNT(*) AS incidents,
               ROUND(AVG(delay_minutes),1) AS avg_delay
        FROM {table} WHERE delay_minutes > 0 AND hour IS NOT NULL AND {where}
        GROUP BY hour ORDER BY hour
    """)
    fig_hourly = go.Figure()
    fig_hourly.add_trace(go.Bar(
        x=hourly["hour"], y=hourly["incidents"],
        marker_color=color, opacity=0.85, name="Incidents",
        hovertemplate="Hour %{x}:00<br>Incidents: %{y}<extra></extra>",
    ))
    peak = hourly.loc[hourly["incidents"].idxmax()]
    fig_hourly.add_trace(go.Bar(
        x=[peak["hour"]], y=[peak["incidents"]],
        marker_color=ACCENT, name=f"Peak: {int(peak['hour']):02d}:00",
        hovertemplate="Peak Hour<br>Incidents: %{y}<extra></extra>",
    ))
    fig_hourly.update_layout(**PLOTLY_THEME, title="Incidents by Hour of Day",
                              barmode="overlay", showlegend=True,
                              legend=dict(bgcolor=CARD_BG))
    fig_hourly.update_xaxes(tickvals=list(range(0,24)),
                             ticktext=[f"{h:02d}" for h in range(0,24)])

    # ── Day of Week ──
    dow = query(f"""
        SELECT day_of_week, COUNT(*) AS incidents
        FROM {table} WHERE delay_minutes > 0 AND {where}
        GROUP BY day_of_week
    """).set_index("day_of_week").reindex(DOW_ORDER).reset_index().fillna(0)

    fig_dow = go.Figure(go.Bar(
        x=[d[:3] for d in DOW_ORDER],
        y=dow["incidents"],
        marker_color=[ACCENT if dow.loc[dow["day_of_week"]==d, "incidents"].values[0]
                      == dow["incidents"].max() else color for d in DOW_ORDER],
        hovertemplate="%{x}<br>Incidents: %{y}<extra></extra>",
    ))
    fig_dow.update_layout(**PLOTLY_THEME, title="Incidents by Day of Week")

    # ── Monthly ──
    monthly = query(f"""
        SELECT year || '-' || printf('%02d', month) AS ym,
               COUNT(*) AS incidents,
               ROUND(AVG(delay_minutes),1) AS avg_delay
        FROM {table} WHERE delay_minutes > 0 AND {where}
        GROUP BY year, month ORDER BY year, month
    """)
    fig_monthly = go.Figure()
    # Convert hex color to rgba for fill
    r = int(color[1:3], 16)
    g = int(color[3:5], 16)
    b = int(color[5:7], 16)
    fill_color = f"rgba({r},{g},{b},0.12)"

    fig_monthly.add_trace(go.Scatter(
        x=monthly["ym"], y=monthly["incidents"],
        mode="lines+markers", line=dict(color=color, width=2),
        marker=dict(size=6), fill="tozeroy",
        fillcolor=fill_color,
        name="Incidents",
        hovertemplate="%{x}<br>Incidents: %{y}<extra></extra>",
    ))
    fig_monthly.update_layout(**PLOTLY_THEME, title="Monthly Incident Trend")
    fig_monthly.update_xaxes(tickangle=45)

    # ── Top routes / stations ──
    if mode == "bus":
        top = query(f"""
            SELECT Line AS name,
                   COUNT(*) AS incidents,
                   ROUND(SUM(delay_minutes)/60.0,1) AS delay_hours
            FROM bus_delays WHERE delay_minutes > 0 AND Line IS NOT NULL AND {where}
            GROUP BY Line ORDER BY delay_hours DESC LIMIT 10
        """).sort_values("delay_hours")
        top_title = "Top 10 Bus Routes · Total Delay Hours"
        top_x     = "delay_hours"
        top_xlabel = "Delay Hours"
    else:
        top = query(f"""
            SELECT REPLACE(station,' STATION','') AS name,
                   COUNT(*) AS incidents,
                   ROUND(AVG(delay_minutes),1) AS avg_delay
            FROM subway_delays WHERE delay_minutes > 0 AND station IS NOT NULL AND {where}
            GROUP BY station ORDER BY incidents DESC LIMIT 10
        """).sort_values("incidents")
        top_title = "Top 10 Subway Stations · Incident Count"
        top_x     = "incidents"
        top_xlabel = "Incidents"

    bar_colors = [ACCENT if i == len(top)-1 else color for i in range(len(top))]
    fig_top = go.Figure(go.Bar(
        x=top[top_x], y=top["name"],
        orientation="h",
        marker_color=bar_colors,
        hovertemplate="%{y}<br>" + top_xlabel + ": %{x}<extra></extra>",
    ))
    fig_top.update_layout(**PLOTLY_THEME, title=top_title,
                           xaxis_title=top_xlabel, height=360)

    # ── Worst delays table ──
    if mode == "bus":
        worst = query(f"""
            SELECT strftime('%Y-%m-%d', date) AS Date, time AS Time,
                   Line AS Route, Station AS Location,
                   Code AS Code, delay_minutes AS "Delay (min)"
            FROM bus_delays WHERE delay_minutes > 0 AND {where}
            ORDER BY delay_minutes DESC LIMIT 50
        """)
    else:
        worst = query(f"""
            SELECT strftime('%Y-%m-%d', date) AS Date, time AS Time,
                   station AS Station, line AS Line,
                   code AS Code, delay_minutes AS "Delay (min)"
            FROM subway_delays WHERE delay_minutes > 0 AND {where}
            ORDER BY delay_minutes DESC LIMIT 50
        """)

    cols = [{"name": c, "id": c} for c in worst.columns]
    return cards, fig_hourly, fig_dow, fig_monthly, fig_top, worst.to_dict("records"), cols


# ── Run ────────────────────────────────────────────────────
if __name__ == "__main__":
    print("=" * 60)
    print("  TTC Delay Analytics — Phase 4: Dashboard")
    print("=" * 60)
    print("\n  Open your browser at: http://127.0.0.1:8050")
    print("  Press Ctrl+C to stop.\n")
    app.run(debug=False)
