"""
=============================================================
TTC Transit Delay Analytics Pipeline
Phase 3: Visualizations
=============================================================
Author : Setu Patel
Requires: ttc_delays.db (generated by phase1_ingest.py)
Output : charts/ folder (6 PNG files)
=============================================================
"""

import os
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import matplotlib.patches as mpatches
import numpy as np

DB_PATH   = "ttc_delays.db"
CHART_DIR = "charts"
os.makedirs(CHART_DIR, exist_ok=True)

# ── Palette & style ────────────────────────────────────────
BUS_COL    = "#E8512A"   # TTC red-orange
SUB_COL    = "#1B6CA8"   # TTC blue
ACCENT     = "#F5C400"   # TTC yellow
BG         = "#0F0F0F"
CARD_BG    = "#1A1A1A"
TEXT       = "#F0F0F0"
GRID       = "#2A2A2A"

plt.rcParams.update({
    "figure.facecolor":  BG,
    "axes.facecolor":    CARD_BG,
    "axes.edgecolor":    GRID,
    "axes.labelcolor":   TEXT,
    "axes.titlecolor":   TEXT,
    "xtick.color":       TEXT,
    "ytick.color":       TEXT,
    "text.color":        TEXT,
    "grid.color":        GRID,
    "grid.linestyle":    "--",
    "grid.alpha":        0.5,
    "font.family":       "DejaVu Sans",
    "axes.spines.top":   False,
    "axes.spines.right": False,
})

def save(fig, name):
    path = os.path.join(CHART_DIR, name)
    fig.savefig(path, dpi=150, bbox_inches="tight", facecolor=BG)
    plt.close(fig)
    print(f"  [saved] {path}")


def load(conn, sql):
    return pd.read_sql(sql, conn)


# ── Chart 1: Bus vs Subway — Head to Head KPI ─────────────
def chart_kpi(conn):
    bus = load(conn, """
        SELECT COUNT(*) AS incidents,
               ROUND(AVG(delay_minutes),1) AS avg_delay,
               ROUND(SUM(delay_minutes)/60.0,0) AS total_hours
        FROM bus_delays WHERE delay_minutes > 0
    """).iloc[0]

    sub = load(conn, """
        SELECT COUNT(*) AS incidents,
               ROUND(AVG(delay_minutes),1) AS avg_delay,
               ROUND(SUM(delay_minutes)/60.0,0) AS total_hours
        FROM subway_delays WHERE delay_minutes > 0
    """).iloc[0]

    fig, axes = plt.subplots(1, 3, figsize=(14, 4))
    fig.suptitle("TTC Delays 2025–2026 · Bus vs Subway", fontsize=15,
                 fontweight="bold", color=ACCENT, y=1.02)

    metrics = [
        ("Total Incidents",    f"{int(bus.incidents):,}",  f"{int(sub.incidents):,}"),
        ("Avg Delay (min)",    str(bus.avg_delay),         str(sub.avg_delay)),
        ("Total Delay (hrs)",  f"{int(bus.total_hours):,}", f"{int(sub.total_hours):,}"),
    ]

    for ax, (title, bval, sval) in zip(axes, metrics):
        ax.set_xlim(0, 1)
        ax.set_ylim(0, 1)
        ax.axis("off")
        ax.set_facecolor(CARD_BG)
        ax.text(0.5, 0.92, title,  ha="center", va="top", fontsize=11,
                color=TEXT, alpha=0.7)
        ax.text(0.25, 0.52, bval,  ha="center", va="center", fontsize=26,
                fontweight="bold", color=BUS_COL)
        ax.text(0.75, 0.52, sval,  ha="center", va="center", fontsize=26,
                fontweight="bold", color=SUB_COL)
        ax.text(0.25, 0.12, "Bus",    ha="center", fontsize=10, color=BUS_COL)
        ax.text(0.75, 0.12, "Subway", ha="center", fontsize=10, color=SUB_COL)
        for spine in ax.spines.values():
            spine.set_visible(False)

    fig.tight_layout()
    save(fig, "01_kpi_summary.png")


# ── Chart 2: Delays by Hour of Day ────────────────────────
def chart_hourly(conn):
    bus = load(conn, """
        SELECT hour, COUNT(*) AS incidents
        FROM bus_delays WHERE delay_minutes > 0 AND hour IS NOT NULL
        GROUP BY hour ORDER BY hour
    """)
    sub = load(conn, """
        SELECT hour, COUNT(*) AS incidents
        FROM subway_delays WHERE delay_minutes > 0 AND hour IS NOT NULL
        GROUP BY hour ORDER BY hour
    """)

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(13, 8), sharex=True)
    fig.suptitle("Incidents by Hour of Day", fontsize=14, fontweight="bold",
                 color=ACCENT)

    for ax, df, color, label in [
        (ax1, bus, BUS_COL, "Bus"),
        (ax2, sub, SUB_COL, "Subway"),
    ]:
        ax.bar(df["hour"], df["incidents"], color=color, alpha=0.85, width=0.7)
        peak_hr = df.loc[df["incidents"].idxmax(), "hour"]
        peak_v  = df["incidents"].max()
        ax.bar(peak_hr, peak_v, color=ACCENT, width=0.7, label=f"Peak: {int(peak_hr):02d}:00")
        ax.set_ylabel("Incidents", color=TEXT)
        ax.set_title(label, color=color, fontsize=12, loc="left")
        ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"{int(x):,}"))
        ax.grid(axis="y")
        ax.legend(facecolor=CARD_BG, edgecolor=GRID, labelcolor=TEXT)

    ax2.set_xlabel("Hour of Day (24h)", color=TEXT)
    ax2.set_xticks(range(0, 24))
    fig.tight_layout()
    save(fig, "02_delays_by_hour.png")


# ── Chart 3: Delays by Day of Week ────────────────────────
def chart_dow(conn):
    DOW_ORDER = ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]

    bus = load(conn, """
        SELECT day_of_week, COUNT(*) AS incidents
        FROM bus_delays WHERE delay_minutes > 0
        GROUP BY day_of_week
    """).set_index("day_of_week").reindex(DOW_ORDER).reset_index()

    sub = load(conn, """
        SELECT day_of_week, COUNT(*) AS incidents
        FROM subway_delays WHERE delay_minutes > 0
        GROUP BY day_of_week
    """).set_index("day_of_week").reindex(DOW_ORDER).reset_index()

    x   = np.arange(len(DOW_ORDER))
    w   = 0.38
    fig, ax = plt.subplots(figsize=(13, 5))
    ax.bar(x - w/2, bus["incidents"], width=w, color=BUS_COL, label="Bus",    alpha=0.9)
    ax.bar(x + w/2, sub["incidents"], width=w, color=SUB_COL, label="Subway", alpha=0.9)
    ax.set_xticks(x)
    ax.set_xticklabels([d[:3] for d in DOW_ORDER])
    ax.set_ylabel("Incidents")
    ax.set_title("Incidents by Day of Week · Bus vs Subway",
                 fontsize=14, fontweight="bold", color=ACCENT)
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"{int(x):,}"))
    ax.grid(axis="y")
    ax.legend(facecolor=CARD_BG, edgecolor=GRID, labelcolor=TEXT)
    fig.tight_layout()
    save(fig, "03_delays_by_dow.png")


# ── Chart 4: Monthly Trend ─────────────────────────────────
def chart_monthly(conn):
    bus = load(conn, """
        SELECT year || '-' || printf('%02d', month) AS ym,
               COUNT(*) AS incidents
        FROM bus_delays WHERE delay_minutes > 0
        GROUP BY year, month ORDER BY year, month
    """)
    sub = load(conn, """
        SELECT year || '-' || printf('%02d', month) AS ym,
               COUNT(*) AS incidents
        FROM subway_delays WHERE delay_minutes > 0
        GROUP BY year, month ORDER BY year, month
    """)

    fig, ax = plt.subplots(figsize=(14, 5))
    ax.plot(bus["ym"], bus["incidents"], color=BUS_COL, marker="o",
            linewidth=2, markersize=5, label="Bus")
    ax.plot(sub["ym"], sub["incidents"], color=SUB_COL, marker="s",
            linewidth=2, markersize=5, label="Subway")
    ax.fill_between(bus["ym"], bus["incidents"], alpha=0.12, color=BUS_COL)
    ax.fill_between(sub["ym"], sub["incidents"], alpha=0.12, color=SUB_COL)
    ax.set_title("Monthly Incident Trend · Jan 2025 – Jan 2026",
                 fontsize=14, fontweight="bold", color=ACCENT)
    ax.set_xlabel("Month")
    ax.set_ylabel("Incidents")
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"{int(x):,}"))
    ax.tick_params(axis="x", rotation=45)
    ax.grid(axis="y")
    ax.legend(facecolor=CARD_BG, edgecolor=GRID, labelcolor=TEXT)
    fig.tight_layout()
    save(fig, "04_monthly_trend.png")


# ── Chart 5: Top 10 Bus Routes ────────────────────────────
def chart_bus_routes(conn):
    df = load(conn, """
        SELECT Line AS route,
               COUNT(*) AS incidents,
               ROUND(SUM(delay_minutes)/60.0, 1) AS delay_hours
        FROM bus_delays WHERE delay_minutes > 0 AND Line IS NOT NULL
        GROUP BY Line ORDER BY delay_hours DESC LIMIT 10
    """)
    df = df.sort_values("delay_hours")

    fig, ax = plt.subplots(figsize=(11, 6))
    bars = ax.barh(df["route"], df["delay_hours"], color=BUS_COL, alpha=0.85)
    bars[-1].set_color(ACCENT)   # highlight worst route
    ax.set_xlabel("Total Delay Hours")
    ax.set_title("Top 10 Bus Routes by Total Delay Hours",
                 fontsize=14, fontweight="bold", color=ACCENT)
    ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"{int(x):,}"))
    for bar, val in zip(bars, df["delay_hours"]):
        ax.text(bar.get_width() + 10, bar.get_y() + bar.get_height()/2,
                f"{val:,.0f}h", va="center", fontsize=8, color=TEXT)
    ax.grid(axis="x")
    fig.tight_layout()
    save(fig, "05_top_bus_routes.png")


# ── Chart 6: Top 10 Subway Stations ───────────────────────
def chart_subway_stations(conn):
    df = load(conn, """
        SELECT REPLACE(station, ' STATION', '') AS station,
               COUNT(*) AS incidents,
               ROUND(AVG(delay_minutes), 1) AS avg_delay
        FROM subway_delays WHERE delay_minutes > 0 AND station IS NOT NULL
        GROUP BY station ORDER BY incidents DESC LIMIT 10
    """)
    df = df.sort_values("incidents")

    fig, ax = plt.subplots(figsize=(11, 6))
    bars = ax.barh(df["station"], df["incidents"], color=SUB_COL, alpha=0.85)
    bars[-1].set_color(ACCENT)
    ax.set_xlabel("Total Incidents")
    ax.set_title("Top 10 Subway Stations by Incident Count",
                 fontsize=14, fontweight="bold", color=ACCENT)
    for bar, val in zip(bars, df["avg_delay"]):
        ax.text(bar.get_width() + 1, bar.get_y() + bar.get_height()/2,
                f"avg {val}m", va="center", fontsize=8, color=TEXT)
    ax.grid(axis="x")
    fig.tight_layout()
    save(fig, "06_top_subway_stations.png")


# ── Main ───────────────────────────────────────────────────
if __name__ == "__main__":
    print("=" * 60)
    print("  TTC Delay Analytics — Phase 3: Visualizations")
    print("=" * 60)

    conn = sqlite3.connect(DB_PATH)

    print("\nGenerating charts ...")
    chart_kpi(conn)
    chart_hourly(conn)
    chart_dow(conn)
    chart_monthly(conn)
    chart_bus_routes(conn)
    chart_subway_stations(conn)

    conn.close()
    print(f"\n✅ Phase 3 complete. All charts saved to '{CHART_DIR}/'")
    print("   Run phase4_dashboard.py next.\n")
