"""
=============================================================
TTC Transit Delay Analytics Pipeline
Phase 2: Exploratory Data Analysis (EDA) & SQL Insights
=============================================================
Author : Setu Patel
Requires: ttc_delays.db (generated by phase1_ingest.py)

Note: Both bus_delays and subway_delays share the same schema:
  date, Line/line, time, day_of_week, Station/station,
  Code/code, delay_minutes, gap_minutes, Bound/direction,
  vehicle_id, year, month, hour
=============================================================
"""

import sqlite3
import pandas as pd

DB_PATH = "ttc_delays.db"


def run_query(conn, sql, title):
    print(f"\n{'─' * 60}")
    print(f"  {title}")
    print('─' * 60)
    df = pd.read_sql(sql, conn)
    print(df.to_string(index=False))
    return df


def eda_bus(conn):
    print("\n" + "=" * 60)
    print("  BUS DELAYS — EDA")
    print("=" * 60)

    run_query(conn, """
        SELECT
            COUNT(*)                              AS total_incidents,
            ROUND(AVG(delay_minutes), 2)          AS avg_delay_min,
            MAX(delay_minutes)                    AS max_delay_min,
            ROUND(SUM(delay_minutes) / 60.0, 1)  AS total_delay_hours
        FROM bus_delays
        WHERE delay_minutes > 0
    """, "1. Overall Bus Delay Summary")

    run_query(conn, """
        SELECT
            Code                            AS delay_code,
            COUNT(*)                        AS incidents,
            ROUND(AVG(delay_minutes), 1)    AS avg_delay_min,
            MAX(delay_minutes)              AS max_delay_min
        FROM bus_delays
        WHERE delay_minutes > 0
          AND Code IS NOT NULL
        GROUP BY Code
        ORDER BY incidents DESC
        LIMIT 10
    """, "2. Top 10 Bus Delay Codes (by frequency)")

    run_query(conn, """
        SELECT
            Line                            AS route,
            COUNT(*)                        AS incidents,
            ROUND(AVG(delay_minutes), 1)    AS avg_delay_min,
            ROUND(SUM(delay_minutes), 0)    AS total_delay_min
        FROM bus_delays
        WHERE delay_minutes > 0
          AND Line IS NOT NULL
        GROUP BY Line
        ORDER BY incidents DESC
        LIMIT 10
    """, "3. Top 10 Worst Bus Routes by Incident Count")

    run_query(conn, """
        SELECT
            day_of_week,
            COUNT(*)                        AS incidents,
            ROUND(AVG(delay_minutes), 1)    AS avg_delay_min
        FROM bus_delays
        WHERE delay_minutes > 0
        GROUP BY day_of_week
        ORDER BY incidents DESC
    """, "4. Bus Delays by Day of Week")

    run_query(conn, """
        SELECT
            hour,
            COUNT(*)                        AS incidents,
            ROUND(AVG(delay_minutes), 1)    AS avg_delay_min
        FROM bus_delays
        WHERE delay_minutes > 0
          AND hour IS NOT NULL
        GROUP BY hour
        ORDER BY hour
    """, "5. Bus Delays by Hour of Day")

    run_query(conn, """
        SELECT
            year,
            month,
            COUNT(*)                        AS incidents,
            ROUND(AVG(delay_minutes), 1)    AS avg_delay_min
        FROM bus_delays
        WHERE delay_minutes > 0
        GROUP BY year, month
        ORDER BY year, month
    """, "6. Bus Delay Monthly Trend")

    run_query(conn, """
        SELECT
            date,
            time,
            Line        AS route,
            Station     AS location,
            Code        AS delay_code,
            delay_minutes
        FROM bus_delays
        ORDER BY delay_minutes DESC
        LIMIT 10
    """, "7. Top 10 Worst Individual Bus Delays")


def eda_subway(conn):
    print("\n" + "=" * 60)
    print("  SUBWAY DELAYS — EDA")
    print("=" * 60)

    run_query(conn, """
        SELECT
            COUNT(*)                              AS total_incidents,
            ROUND(AVG(delay_minutes), 2)          AS avg_delay_min,
            MAX(delay_minutes)                    AS max_delay_min,
            ROUND(SUM(delay_minutes) / 60.0, 1)  AS total_delay_hours
        FROM subway_delays
        WHERE delay_minutes > 0
    """, "1. Overall Subway Delay Summary")

    run_query(conn, """
        SELECT
            code,
            COUNT(*)                        AS incidents,
            ROUND(AVG(delay_minutes), 1)    AS avg_delay_min,
            MAX(delay_minutes)              AS max_delay_min
        FROM subway_delays
        WHERE delay_minutes > 0
          AND code IS NOT NULL
        GROUP BY code
        ORDER BY incidents DESC
        LIMIT 10
    """, "2. Top 10 Subway Delay Codes (by frequency)")

    run_query(conn, """
        SELECT
            line,
            COUNT(*)                        AS incidents,
            ROUND(AVG(delay_minutes), 1)    AS avg_delay_min,
            ROUND(SUM(delay_minutes), 0)    AS total_delay_min
        FROM subway_delays
        WHERE delay_minutes > 0
          AND line IS NOT NULL
        GROUP BY line
        ORDER BY incidents DESC
    """, "3. Subway Delays by Line")

    run_query(conn, """
        SELECT
            station,
            COUNT(*)                        AS incidents,
            ROUND(AVG(delay_minutes), 1)    AS avg_delay_min,
            ROUND(SUM(delay_minutes), 0)    AS total_delay_min
        FROM subway_delays
        WHERE delay_minutes > 0
          AND station IS NOT NULL
        GROUP BY station
        ORDER BY incidents DESC
        LIMIT 10
    """, "4. Top 10 Worst Subway Stations by Incident Count")

    run_query(conn, """
        SELECT
            day_of_week,
            COUNT(*)                        AS incidents,
            ROUND(AVG(delay_minutes), 1)    AS avg_delay_min
        FROM subway_delays
        WHERE delay_minutes > 0
        GROUP BY day_of_week
        ORDER BY incidents DESC
    """, "5. Subway Delays by Day of Week")

    run_query(conn, """
        SELECT
            hour,
            COUNT(*)                        AS incidents,
            ROUND(AVG(delay_minutes), 1)    AS avg_delay_min
        FROM subway_delays
        WHERE delay_minutes > 0
          AND hour IS NOT NULL
        GROUP BY hour
        ORDER BY hour
    """, "6. Subway Delays by Hour of Day")

    run_query(conn, """
        SELECT
            year,
            month,
            COUNT(*)                        AS incidents,
            ROUND(AVG(delay_minutes), 1)    AS avg_delay_min
        FROM subway_delays
        WHERE delay_minutes > 0
        GROUP BY year, month
        ORDER BY year, month
    """, "7. Subway Delay Monthly Trend")

    run_query(conn, """
        SELECT
            date,
            time,
            station,
            line,
            code,
            delay_minutes
        FROM subway_delays
        ORDER BY delay_minutes DESC
        LIMIT 10
    """, "8. Top 10 Worst Individual Subway Delays")


def eda_combined(conn):
    print("\n" + "=" * 60)
    print("  COMBINED INSIGHTS — Bus vs Subway")
    print("=" * 60)

    run_query(conn, """
        SELECT 'Bus'    AS mode, ROUND(AVG(delay_minutes), 2) AS avg_delay_min,
               COUNT(*) AS total_incidents,
               ROUND(SUM(delay_minutes)/60.0, 1) AS total_delay_hours
        FROM bus_delays WHERE delay_minutes > 0
        UNION ALL
        SELECT 'Subway', ROUND(AVG(delay_minutes), 2),
               COUNT(*),
               ROUND(SUM(delay_minutes)/60.0, 1)
        FROM subway_delays WHERE delay_minutes > 0
    """, "9. Bus vs Subway — Head to Head Summary")

    run_query(conn, """
        SELECT 'Bus' AS mode, hour, COUNT(*) AS incidents
        FROM bus_delays
        WHERE delay_minutes > 0 AND hour IS NOT NULL
        GROUP BY hour
        ORDER BY incidents DESC
        LIMIT 1
    """, "10a. Bus — Single Peak Delay Hour")

    run_query(conn, """
        SELECT 'Subway' AS mode, hour, COUNT(*) AS incidents
        FROM subway_delays
        WHERE delay_minutes > 0 AND hour IS NOT NULL
        GROUP BY hour
        ORDER BY incidents DESC
        LIMIT 1
    """, "10b. Subway — Single Peak Delay Hour")


# ── Main ───────────────────────────────────────────────────
if __name__ == "__main__":
    print("=" * 60)
    print("  TTC Delay Analytics — Phase 2: EDA")
    print("=" * 60)

    conn = sqlite3.connect(DB_PATH)

    eda_bus(conn)
    eda_subway(conn)
    eda_combined(conn)

    conn.close()
    print("\n✅ Phase 2 complete. Run phase3_viz.py next.\n")
